//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual State State { get; set; }
        public virtual State State1 { get; set; }
        public virtual State State2 { get; set; }
        public virtual State State3 { get; set; }
        public virtual State State4 { get; set; }
        public virtual State State5 { get; set; }
        public virtual State State6 { get; set; }
        public virtual State State7 { get; set; }
        public virtual State State8 { get; set; }
        public virtual State State9 { get; set; }
        public virtual State State10 { get; set; }
    }
}
