//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShoppingCartEntities : DbContext
    {
        public ShoppingCartEntities()
            : base("name=ShoppingCartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Exception> Exceptions { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderMaster> OrderMasters { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ResetPasswordRequest> ResetPasswordRequests { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Temp> Temps { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<ViewProductDetail> ViewProductDetails { get; set; }
    
        public virtual ObjectResult<GetCartProducts_Result> GetCartProducts(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartProducts_Result>("GetCartProducts", userIdParameter);
        }
    
        public virtual ObjectResult<GetCountryNames_Result> GetCountryNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountryNames_Result>("GetCountryNames");
        }
    
        public virtual int STP_AddNewProduct(Nullable<int> categoryId, string productName, Nullable<System.DateTime> createdOn, Nullable<decimal> price, string productDescription, Nullable<bool> isActive)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("productName", productName) :
                new ObjectParameter("productName", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("createdOn", createdOn) :
                new ObjectParameter("createdOn", typeof(System.DateTime));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(decimal));
    
            var productDescriptionParameter = productDescription != null ?
                new ObjectParameter("productDescription", productDescription) :
                new ObjectParameter("productDescription", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_AddNewProduct", categoryIdParameter, productNameParameter, createdOnParameter, priceParameter, productDescriptionParameter, isActiveParameter);
        }
    
        public virtual int STP_AddOrder(Nullable<int> userId, Nullable<decimal> grossAmount, string receiverMobileNumber, string billingMode, string shippingAddress, Nullable<System.DateTime> orderDate, string orderStatus, string receiverEmailId, string receiverFirstName, string receiverLastName)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var grossAmountParameter = grossAmount.HasValue ?
                new ObjectParameter("grossAmount", grossAmount) :
                new ObjectParameter("grossAmount", typeof(decimal));
    
            var receiverMobileNumberParameter = receiverMobileNumber != null ?
                new ObjectParameter("receiverMobileNumber", receiverMobileNumber) :
                new ObjectParameter("receiverMobileNumber", typeof(string));
    
            var billingModeParameter = billingMode != null ?
                new ObjectParameter("billingMode", billingMode) :
                new ObjectParameter("billingMode", typeof(string));
    
            var shippingAddressParameter = shippingAddress != null ?
                new ObjectParameter("shippingAddress", shippingAddress) :
                new ObjectParameter("shippingAddress", typeof(string));
    
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("orderDate", orderDate) :
                new ObjectParameter("orderDate", typeof(System.DateTime));
    
            var orderStatusParameter = orderStatus != null ?
                new ObjectParameter("orderStatus", orderStatus) :
                new ObjectParameter("orderStatus", typeof(string));
    
            var receiverEmailIdParameter = receiverEmailId != null ?
                new ObjectParameter("receiverEmailId", receiverEmailId) :
                new ObjectParameter("receiverEmailId", typeof(string));
    
            var receiverFirstNameParameter = receiverFirstName != null ?
                new ObjectParameter("receiverFirstName", receiverFirstName) :
                new ObjectParameter("receiverFirstName", typeof(string));
    
            var receiverLastNameParameter = receiverLastName != null ?
                new ObjectParameter("receiverLastName", receiverLastName) :
                new ObjectParameter("receiverLastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_AddOrder", userIdParameter, grossAmountParameter, receiverMobileNumberParameter, billingModeParameter, shippingAddressParameter, orderDateParameter, orderStatusParameter, receiverEmailIdParameter, receiverFirstNameParameter, receiverLastNameParameter);
        }
    
        public virtual int STP_AddProductsToCart(Nullable<int> productId, Nullable<int> userId, Nullable<int> quantity, Nullable<decimal> price)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_AddProductsToCart", productIdParameter, userIdParameter, quantityParameter, priceParameter);
        }
    
        public virtual int STP_DeleteCartProducts(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteCartProducts", userIdParameter);
        }
    
        public virtual int STP_DeleteCategory(Nullable<int> categoryId, Nullable<System.DateTime> deletedOn)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var deletedOnParameter = deletedOn.HasValue ?
                new ObjectParameter("deletedOn", deletedOn) :
                new ObjectParameter("deletedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteCategory", categoryIdParameter, deletedOnParameter);
        }
    
        public virtual int STP_DeleteCity(Nullable<int> id, Nullable<System.DateTime> deletedOn)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var deletedOnParameter = deletedOn.HasValue ?
                new ObjectParameter("deletedOn", deletedOn) :
                new ObjectParameter("deletedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteCity", idParameter, deletedOnParameter);
        }
    
        public virtual int STP_DeleteCountry(Nullable<int> id, Nullable<System.DateTime> deletedOn)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var deletedOnParameter = deletedOn.HasValue ?
                new ObjectParameter("deletedOn", deletedOn) :
                new ObjectParameter("deletedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteCountry", idParameter, deletedOnParameter);
        }
    
        public virtual int STP_DeleteException(Nullable<int> exceptionId)
        {
            var exceptionIdParameter = exceptionId.HasValue ?
                new ObjectParameter("exceptionId", exceptionId) :
                new ObjectParameter("exceptionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteException", exceptionIdParameter);
        }
    
        public virtual int STP_DeleteProduct(Nullable<int> productId, Nullable<System.DateTime> deletedOn)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            var deletedOnParameter = deletedOn.HasValue ?
                new ObjectParameter("deletedOn", deletedOn) :
                new ObjectParameter("deletedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteProduct", productIdParameter, deletedOnParameter);
        }
    
        public virtual int STP_DeleteProductFromCart(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteProductFromCart", productIdParameter);
        }
    
        public virtual int STP_DeleteProductImage(Nullable<int> imageId)
        {
            var imageIdParameter = imageId.HasValue ?
                new ObjectParameter("imageId", imageId) :
                new ObjectParameter("imageId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteProductImage", imageIdParameter);
        }
    
        public virtual int STP_DeleteState(Nullable<int> id, Nullable<System.DateTime> deletedOn)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var deletedOnParameter = deletedOn.HasValue ?
                new ObjectParameter("deletedOn", deletedOn) :
                new ObjectParameter("deletedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteState", idParameter, deletedOnParameter);
        }
    
        public virtual int STP_DeleteSubCategory(Nullable<int> subCategoryId)
        {
            var subCategoryIdParameter = subCategoryId.HasValue ?
                new ObjectParameter("subCategoryId", subCategoryId) :
                new ObjectParameter("subCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteSubCategory", subCategoryIdParameter);
        }
    
        public virtual int STP_DeleteUser(Nullable<int> userId, Nullable<System.DateTime> deletedOn)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var deletedOnParameter = deletedOn.HasValue ?
                new ObjectParameter("deletedOn", deletedOn) :
                new ObjectParameter("deletedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteUser", userIdParameter, deletedOnParameter);
        }
    
        public virtual ObjectResult<STP_GetActiveCities_Result> STP_GetActiveCities(Nullable<int> stateId)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetActiveCities_Result>("STP_GetActiveCities", stateIdParameter);
        }
    
        public virtual ObjectResult<STP_GetActiveCountries_Result> STP_GetActiveCountries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetActiveCountries_Result>("STP_GetActiveCountries");
        }
    
        public virtual ObjectResult<STP_GetActiveStates_Result> STP_GetActiveStates(Nullable<int> countryId)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("countryId", countryId) :
                new ObjectParameter("countryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetActiveStates_Result>("STP_GetActiveStates", countryIdParameter);
        }
    
        public virtual ObjectResult<STP_GetAllCities_Result> STP_GetAllCities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetAllCities_Result>("STP_GetAllCities");
        }
    
        public virtual ObjectResult<STP_GetAllStates_Result> STP_GetAllStates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetAllStates_Result>("STP_GetAllStates");
        }
    
        public virtual ObjectResult<STP_GetAllSubCategories_Result> STP_GetAllSubCategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetAllSubCategories_Result>("STP_GetAllSubCategories");
        }
    
        public virtual ObjectResult<STP_GetCartProduct_Result> STP_GetCartProduct(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetCartProduct_Result>("STP_GetCartProduct", productIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> STP_GetCategoryId(Nullable<int> subCategoryId)
        {
            var subCategoryIdParameter = subCategoryId.HasValue ?
                new ObjectParameter("subCategoryId", subCategoryId) :
                new ObjectParameter("subCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("STP_GetCategoryId", subCategoryIdParameter);
        }
    
        public virtual ObjectResult<STP_GetCategoryIdAndSubCategoryID_Result> STP_GetCategoryIdAndSubCategoryID(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetCategoryIdAndSubCategoryID_Result>("STP_GetCategoryIdAndSubCategoryID", productIdParameter);
        }
    
        public virtual ObjectResult<STP_GetCategoryName_Result> STP_GetCategoryName(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetCategoryName_Result>("STP_GetCategoryName", categoryIdParameter);
        }
    
        public virtual ObjectResult<STP_GetCities_Result> STP_GetCities(Nullable<int> stateId)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetCities_Result>("STP_GetCities", stateIdParameter);
        }
    
        public virtual ObjectResult<STP_GetCitiesForCountry_Result> STP_GetCitiesForCountry(Nullable<int> countryId)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("countryId", countryId) :
                new ObjectParameter("countryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetCitiesForCountry_Result>("STP_GetCitiesForCountry", countryIdParameter);
        }
    
        public virtual ObjectResult<STP_GetCityDetails_Result> STP_GetCityDetails(Nullable<int> cityId)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("cityId", cityId) :
                new ObjectParameter("cityId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetCityDetails_Result>("STP_GetCityDetails", cityIdParameter);
        }
    
        public virtual ObjectResult<STP_GetCountryDetails_Result> STP_GetCountryDetails(Nullable<int> countryId)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("countryId", countryId) :
                new ObjectParameter("countryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetCountryDetails_Result>("STP_GetCountryDetails", countryIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> STP_GetCountryId(Nullable<int> stateId)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("STP_GetCountryId", stateIdParameter);
        }
    
        public virtual ObjectResult<string> STP_GetEmailIdList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("STP_GetEmailIdList");
        }
    
        public virtual int STP_GetException(string type, string details, string fileName, string method, Nullable<System.DateTime> datetime)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var detailsParameter = details != null ?
                new ObjectParameter("details", details) :
                new ObjectParameter("details", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("fileName", fileName) :
                new ObjectParameter("fileName", typeof(string));
    
            var methodParameter = method != null ?
                new ObjectParameter("method", method) :
                new ObjectParameter("method", typeof(string));
    
            var datetimeParameter = datetime.HasValue ?
                new ObjectParameter("datetime", datetime) :
                new ObjectParameter("datetime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_GetException", typeParameter, detailsParameter, fileNameParameter, methodParameter, datetimeParameter);
        }
    
        public virtual ObjectResult<STP_GetExceptionDetails_Result> STP_GetExceptionDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetExceptionDetails_Result>("STP_GetExceptionDetails");
        }
    
        public virtual ObjectResult<STP_GetProductsByCategory_Result> STP_GetProductsByCategory(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetProductsByCategory_Result>("STP_GetProductsByCategory", categoryIdParameter);
        }
    
        public virtual ObjectResult<STP_GetProductsBySubCategory_Result> STP_GetProductsBySubCategory(Nullable<int> subCategoryId)
        {
            var subCategoryIdParameter = subCategoryId.HasValue ?
                new ObjectParameter("subCategoryId", subCategoryId) :
                new ObjectParameter("subCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetProductsBySubCategory_Result>("STP_GetProductsBySubCategory", subCategoryIdParameter);
        }
    
        public virtual ObjectResult<STP_GetResetRequestDetails_Result> STP_GetResetRequestDetails(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetResetRequestDetails_Result>("STP_GetResetRequestDetails", idParameter);
        }
    
        public virtual ObjectResult<STP_GetRoleList_Result> STP_GetRoleList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetRoleList_Result>("STP_GetRoleList");
        }
    
        public virtual ObjectResult<STP_GetStateDetails_Result> STP_GetStateDetails(Nullable<int> stateId)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetStateDetails_Result>("STP_GetStateDetails", stateIdParameter);
        }
    
        public virtual ObjectResult<STP_GetStates_Result> STP_GetStates(Nullable<int> countryId)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("countryId", countryId) :
                new ObjectParameter("countryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetStates_Result>("STP_GetStates", countryIdParameter);
        }
    
        public virtual ObjectResult<STP_GetSubCategoryDetails_Result> STP_GetSubCategoryDetails(Nullable<int> subCategoryId)
        {
            var subCategoryIdParameter = subCategoryId.HasValue ?
                new ObjectParameter("subCategoryId", subCategoryId) :
                new ObjectParameter("subCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetSubCategoryDetails_Result>("STP_GetSubCategoryDetails", subCategoryIdParameter);
        }
    
        public virtual ObjectResult<STP_GetUserDetails_Result> STP_GetUserDetails(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetUserDetails_Result>("STP_GetUserDetails", userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> STP_GetUserIdViaEmailId(string emailId)
        {
            var emailIdParameter = emailId != null ?
                new ObjectParameter("emailId", emailId) :
                new ObjectParameter("emailId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("STP_GetUserIdViaEmailId", emailIdParameter);
        }
    
        public virtual ObjectResult<string> STP_GetUserName(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("STP_GetUserName", userIdParameter);
        }
    
        public virtual ObjectResult<STP_GetUsers_Result> STP_GetUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetUsers_Result>("STP_GetUsers");
        }
    
        public virtual int STP_InsertCategories(string categoryName, Nullable<System.DateTime> createdOn, Nullable<bool> isActive)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("createdOn", createdOn) :
                new ObjectParameter("createdOn", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_InsertCategories", categoryNameParameter, createdOnParameter, isActiveParameter);
        }
    
        public virtual int STP_InsertCity(Nullable<int> stateId, string cityName, Nullable<System.DateTime> createdOn)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            var cityNameParameter = cityName != null ?
                new ObjectParameter("cityName", cityName) :
                new ObjectParameter("cityName", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("createdOn", createdOn) :
                new ObjectParameter("createdOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_InsertCity", stateIdParameter, cityNameParameter, createdOnParameter);
        }
    
        public virtual int STP_InsertCountry(string countryName, Nullable<System.DateTime> createdOn)
        {
            var countryNameParameter = countryName != null ?
                new ObjectParameter("countryName", countryName) :
                new ObjectParameter("countryName", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("createdOn", createdOn) :
                new ObjectParameter("createdOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_InsertCountry", countryNameParameter, createdOnParameter);
        }
    
        public virtual int STP_InsertProduct(Nullable<int> categoryId, string productName, Nullable<System.DateTime> createdOn, Nullable<decimal> price, string productDescription, Nullable<bool> isActive, Nullable<int> quantity)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("productName", productName) :
                new ObjectParameter("productName", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("createdOn", createdOn) :
                new ObjectParameter("createdOn", typeof(System.DateTime));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(decimal));
    
            var productDescriptionParameter = productDescription != null ?
                new ObjectParameter("productDescription", productDescription) :
                new ObjectParameter("productDescription", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_InsertProduct", categoryIdParameter, productNameParameter, createdOnParameter, priceParameter, productDescriptionParameter, isActiveParameter, quantityParameter);
        }
    
        public virtual int STP_InsertState(Nullable<int> countryId, string stateName, Nullable<System.DateTime> createdOn)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("countryId", countryId) :
                new ObjectParameter("countryId", typeof(int));
    
            var stateNameParameter = stateName != null ?
                new ObjectParameter("stateName", stateName) :
                new ObjectParameter("stateName", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("createdOn", createdOn) :
                new ObjectParameter("createdOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_InsertState", countryIdParameter, stateNameParameter, createdOnParameter);
        }
    
        public virtual int STP_InsertSubCategories(Nullable<int> categoryId, string subCategoryName, Nullable<System.DateTime> createdOn, Nullable<System.DateTime> modifiedOn, Nullable<bool> isActive)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var subCategoryNameParameter = subCategoryName != null ?
                new ObjectParameter("subCategoryName", subCategoryName) :
                new ObjectParameter("subCategoryName", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("createdOn", createdOn) :
                new ObjectParameter("createdOn", typeof(System.DateTime));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("modifiedOn", modifiedOn) :
                new ObjectParameter("modifiedOn", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_InsertSubCategories", categoryIdParameter, subCategoryNameParameter, createdOnParameter, modifiedOnParameter, isActiveParameter);
        }
    
        public virtual int STP_InsertUser(Nullable<int> roleId, string emailId, string userPassWord, Nullable<System.DateTime> createdOn, Nullable<bool> isActive, string firstName, string lastName, string permanentAddress, string alternateAddress, string mobileNumber)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("emailId", emailId) :
                new ObjectParameter("emailId", typeof(string));
    
            var userPassWordParameter = userPassWord != null ?
                new ObjectParameter("userPassWord", userPassWord) :
                new ObjectParameter("userPassWord", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("createdOn", createdOn) :
                new ObjectParameter("createdOn", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var permanentAddressParameter = permanentAddress != null ?
                new ObjectParameter("permanentAddress", permanentAddress) :
                new ObjectParameter("permanentAddress", typeof(string));
    
            var alternateAddressParameter = alternateAddress != null ?
                new ObjectParameter("alternateAddress", alternateAddress) :
                new ObjectParameter("alternateAddress", typeof(string));
    
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("mobileNumber", mobileNumber) :
                new ObjectParameter("mobileNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_InsertUser", roleIdParameter, emailIdParameter, userPassWordParameter, createdOnParameter, isActiveParameter, firstNameParameter, lastNameParameter, permanentAddressParameter, alternateAddressParameter, mobileNumberParameter);
        }
    
        public virtual ObjectResult<STP_LoginUser_Result> STP_LoginUser(string emailId, string password)
        {
            var emailIdParameter = emailId != null ?
                new ObjectParameter("emailId", emailId) :
                new ObjectParameter("emailId", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_LoginUser_Result>("STP_LoginUser", emailIdParameter, passwordParameter);
        }
    
        public virtual ObjectResult<STP_ProductDetails_Result> STP_ProductDetails(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_ProductDetails_Result>("STP_ProductDetails", productIdParameter);
        }
    
        public virtual ObjectResult<STP_RandomProducts_Result> STP_RandomProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_RandomProducts_Result>("STP_RandomProducts");
        }
    
        public virtual int STP_RegisterCustomer(Nullable<int> roleId, string emailId, string userPassWord, Nullable<System.DateTime> createdOn, Nullable<bool> isActive, string firstName, string lastName, string permanentAddress, string alternateAddress, string mobileNumber)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("emailId", emailId) :
                new ObjectParameter("emailId", typeof(string));
    
            var userPassWordParameter = userPassWord != null ?
                new ObjectParameter("userPassWord", userPassWord) :
                new ObjectParameter("userPassWord", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("createdOn", createdOn) :
                new ObjectParameter("createdOn", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var permanentAddressParameter = permanentAddress != null ?
                new ObjectParameter("permanentAddress", permanentAddress) :
                new ObjectParameter("permanentAddress", typeof(string));
    
            var alternateAddressParameter = alternateAddress != null ?
                new ObjectParameter("alternateAddress", alternateAddress) :
                new ObjectParameter("alternateAddress", typeof(string));
    
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("mobileNumber", mobileNumber) :
                new ObjectParameter("mobileNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_RegisterCustomer", roleIdParameter, emailIdParameter, userPassWordParameter, createdOnParameter, isActiveParameter, firstNameParameter, lastNameParameter, permanentAddressParameter, alternateAddressParameter, mobileNumberParameter);
        }
    
        public virtual int STP_RemoveProductFromCart(Nullable<int> productId, Nullable<int> userId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_RemoveProductFromCart", productIdParameter, userIdParameter);
        }
    
        public virtual ObjectResult<STP_ResetPassword_Result> STP_ResetPassword(string emailId)
        {
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_ResetPassword_Result>("STP_ResetPassword", emailIdParameter);
        }
    
        public virtual ObjectResult<STP_Search_Result> STP_Search(string value)
        {
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_Search_Result>("STP_Search", valueParameter);
        }
    
        public virtual ObjectResult<STP_SearchActiveProducts_Result> STP_SearchActiveProducts(string value)
        {
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_SearchActiveProducts_Result>("STP_SearchActiveProducts", valueParameter);
        }
    
        public virtual ObjectResult<STP_ShowAllProductList_Result> STP_ShowAllProductList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_ShowAllProductList_Result>("STP_ShowAllProductList");
        }
    
        public virtual ObjectResult<STP_ShowAllProductsForCategory_Result> STP_ShowAllProductsForCategory(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_ShowAllProductsForCategory_Result>("STP_ShowAllProductsForCategory", categoryIdParameter);
        }
    
        public virtual ObjectResult<STP_ShowCategoryList_Result> STP_ShowCategoryList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_ShowCategoryList_Result>("STP_ShowCategoryList");
        }
    
        public virtual ObjectResult<STP_ShowOrderDetails_Result> STP_ShowOrderDetails(Nullable<int> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_ShowOrderDetails_Result>("STP_ShowOrderDetails", orderIdParameter);
        }
    
        public virtual ObjectResult<STP_ShowOrderProducts_Result> STP_ShowOrderProducts(Nullable<int> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_ShowOrderProducts_Result>("STP_ShowOrderProducts", orderIdParameter);
        }
    
        public virtual ObjectResult<STP_ShowOrders_Result> STP_ShowOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_ShowOrders_Result>("STP_ShowOrders");
        }
    
        public virtual ObjectResult<STP_ShowProductImages_Result> STP_ShowProductImages(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_ShowProductImages_Result>("STP_ShowProductImages", productIdParameter);
        }
    
        public virtual ObjectResult<STP_ShowProductList_Result> STP_ShowProductList(Nullable<int> subCategoryId)
        {
            var subCategoryIdParameter = subCategoryId.HasValue ?
                new ObjectParameter("subCategoryId", subCategoryId) :
                new ObjectParameter("subCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_ShowProductList_Result>("STP_ShowProductList", subCategoryIdParameter);
        }
    
        public virtual ObjectResult<STP_ShowSubCategoryList_Result> STP_ShowSubCategoryList(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_ShowSubCategoryList_Result>("STP_ShowSubCategoryList", categoryIdParameter);
        }
    
        public virtual int STP_UpdateCart(Nullable<int> productId, Nullable<int> quantity, Nullable<decimal> price, Nullable<int> userId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(decimal));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateCart", productIdParameter, quantityParameter, priceParameter, userIdParameter);
        }
    
        public virtual int STP_UpdateCategories(Nullable<int> categoryId, string categoryName, Nullable<System.DateTime> modifiedOn, Nullable<bool> isActive)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("modifiedOn", modifiedOn) :
                new ObjectParameter("modifiedOn", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateCategories", categoryIdParameter, categoryNameParameter, modifiedOnParameter, isActiveParameter);
        }
    
        public virtual int STP_UpdateCity(Nullable<int> cityId, Nullable<int> stateId, string newName, Nullable<bool> isActive, Nullable<System.DateTime> modifiedOn)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("cityId", cityId) :
                new ObjectParameter("cityId", typeof(int));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            var newNameParameter = newName != null ?
                new ObjectParameter("newName", newName) :
                new ObjectParameter("newName", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("modifiedOn", modifiedOn) :
                new ObjectParameter("modifiedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateCity", cityIdParameter, stateIdParameter, newNameParameter, isActiveParameter, modifiedOnParameter);
        }
    
        public virtual int STP_UpdateCountry(Nullable<int> id, string newName, Nullable<bool> isActive, Nullable<System.DateTime> modifiedOn)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var newNameParameter = newName != null ?
                new ObjectParameter("newName", newName) :
                new ObjectParameter("newName", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("modifiedOn", modifiedOn) :
                new ObjectParameter("modifiedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateCountry", idParameter, newNameParameter, isActiveParameter, modifiedOnParameter);
        }
    
        public virtual int STP_UpdateNewPassword(string emailId, string password)
        {
            var emailIdParameter = emailId != null ?
                new ObjectParameter("emailId", emailId) :
                new ObjectParameter("emailId", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateNewPassword", emailIdParameter, passwordParameter);
        }
    
        public virtual int STP_UpdateProduct(Nullable<int> productId, Nullable<int> categoryId, string productName, Nullable<System.DateTime> modifiedOn, Nullable<decimal> price, string productDescription, Nullable<bool> isActive)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("productName", productName) :
                new ObjectParameter("productName", typeof(string));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("modifiedOn", modifiedOn) :
                new ObjectParameter("modifiedOn", typeof(System.DateTime));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(decimal));
    
            var productDescriptionParameter = productDescription != null ?
                new ObjectParameter("productDescription", productDescription) :
                new ObjectParameter("productDescription", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateProduct", productIdParameter, categoryIdParameter, productNameParameter, modifiedOnParameter, priceParameter, productDescriptionParameter, isActiveParameter);
        }
    
        public virtual int STP_UpdateProductDetails(Nullable<int> productId, Nullable<int> subCategoryId, string productName, Nullable<System.DateTime> modifiedOn, Nullable<decimal> price, string productDescription, Nullable<bool> isActive)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            var subCategoryIdParameter = subCategoryId.HasValue ?
                new ObjectParameter("subCategoryId", subCategoryId) :
                new ObjectParameter("subCategoryId", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("productName", productName) :
                new ObjectParameter("productName", typeof(string));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("modifiedOn", modifiedOn) :
                new ObjectParameter("modifiedOn", typeof(System.DateTime));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(decimal));
    
            var productDescriptionParameter = productDescription != null ?
                new ObjectParameter("productDescription", productDescription) :
                new ObjectParameter("productDescription", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateProductDetails", productIdParameter, subCategoryIdParameter, productNameParameter, modifiedOnParameter, priceParameter, productDescriptionParameter, isActiveParameter);
        }
    
        public virtual int STP_UpdateState(Nullable<int> id, string newName, Nullable<int> countryId, Nullable<bool> isActive, Nullable<System.DateTime> modifiedOn)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var newNameParameter = newName != null ?
                new ObjectParameter("newName", newName) :
                new ObjectParameter("newName", typeof(string));
    
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("countryId", countryId) :
                new ObjectParameter("countryId", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("modifiedOn", modifiedOn) :
                new ObjectParameter("modifiedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateState", idParameter, newNameParameter, countryIdParameter, isActiveParameter, modifiedOnParameter);
        }
    
        public virtual int STP_UpdateSubCategories(Nullable<int> subCategoryId, Nullable<int> categoryId, string subCategoryName, Nullable<System.DateTime> modifiedOn, Nullable<bool> isActive)
        {
            var subCategoryIdParameter = subCategoryId.HasValue ?
                new ObjectParameter("subCategoryId", subCategoryId) :
                new ObjectParameter("subCategoryId", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var subCategoryNameParameter = subCategoryName != null ?
                new ObjectParameter("subCategoryName", subCategoryName) :
                new ObjectParameter("subCategoryName", typeof(string));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("modifiedOn", modifiedOn) :
                new ObjectParameter("modifiedOn", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateSubCategories", subCategoryIdParameter, categoryIdParameter, subCategoryNameParameter, modifiedOnParameter, isActiveParameter);
        }
    
        public virtual int STP_UpdateUser(Nullable<int> userId, Nullable<int> roleId, Nullable<bool> isActive, Nullable<System.DateTime> modifiedOn)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("modifiedOn", modifiedOn) :
                new ObjectParameter("modifiedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateUser", userIdParameter, roleIdParameter, isActiveParameter, modifiedOnParameter);
        }
    
        public virtual int STP_UpdateUserProfile(Nullable<int> userId, Nullable<System.DateTime> modifiedOn, string firstName, string lastName, string permanentAddress, string alternateAddress, string mobileNumber)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("modifiedOn", modifiedOn) :
                new ObjectParameter("modifiedOn", typeof(System.DateTime));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var permanentAddressParameter = permanentAddress != null ?
                new ObjectParameter("permanentAddress", permanentAddress) :
                new ObjectParameter("permanentAddress", typeof(string));
    
            var alternateAddressParameter = alternateAddress != null ?
                new ObjectParameter("alternateAddress", alternateAddress) :
                new ObjectParameter("alternateAddress", typeof(string));
    
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("mobileNumber", mobileNumber) :
                new ObjectParameter("mobileNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateUserProfile", userIdParameter, modifiedOnParameter, firstNameParameter, lastNameParameter, permanentAddressParameter, alternateAddressParameter, mobileNumberParameter);
        }
    }
}
